services:
  kafka:
    image: ${COMPOSE_KAFKA_IMAGE:-apache/kafka-native}:${COMPOSE_KAFKA_VERSION:-latest}
    hostname: kafka
    ports:
      - ${COMPOSE_KAFKA_PORT:-9092}:${COMPOSE_KAFKA_PORT:-9092}
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091,PLAINTEXT_HOST://localhost:${COMPOSE_KAFKA_PORT:-9092}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9091,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      #KAFKA_DELETE_TOPIC_ENABLE: "true"
      #KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      #KAFKA_SCHEMA_REGISTRY_URL: schema-registry:${COMPOSE_SCHEMA_REGISTRY_PORT:-8081}
      #KAFKA_JMX_PORT: 9991
